# -*- coding: utf-8 -*-
"""amazon flipkart matching.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Q41ZTU_D5UbtGUXEYdvZJJsMKqhfI6v
"""

import pandas as pd

Flipkart = pd.read_csv('/content/drive/MyDrive/flipkart_com-ecommerce_sample.csv')
Flipkart

Flipkart.columns

Flipkart = Flipkart[['product_name','retail_price','discounted_price']]

Flipkart.rename(columns = {'product_name':'Product name in Flipkar','retail_price':'Retail Price in Flipkart',
                        'discounted_price':'Discounted Price in Flipkart'}, inplace = True)

Flipkart

Flipkart.isna().sum()

mean1 = Flipkart['Retail Price in Flipkart'].mean().round()
 mean1

Flipkart['Retail Price in Flipkart'].fillna(value=mean1, inplace=True)

Flipkart.isna().sum()

mean2 = Flipkart['Discounted Price in Flipkart'].mean().round()
Flipkart['Discounted Price in Flipkart'].fillna(value=mean2, inplace=True)

Flipkart.isna().sum()

Amazon = pd.read_csv('/content/drive/MyDrive/amz_com-ecommerce_sample.csv',encoding= 'unicode_escape')
Amazon.head()

Amazon.columns

Amazon = Amazon[['product_name','retail_price','discounted_price']]

Amazon.rename(columns = {'product_name':'Product name in Amazon','retail_price':'Retail Price in Amazon',
                        'discounted_price':'Discounted Price in Amazon'}, inplace = True)

Amazon

Amazon.isna().sum()

result = pd.concat([Flipkart, Amazon], axis=1)
result.head()