# -*- coding: utf-8 -*-
"""amazon flipkart matching.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Q41ZTU_D5UbtGUXEYdvZJJsMKqhfI6v
"""

import pandas as pd #importing pandas library

Flipkart = pd.read_csv('/content/drive/MyDrive/flipkart_com-ecommerce_sample.csv') # importing flipkart dataset
Flipkart

Flipkart.columns

# Selecting important column for dataset

Flipkart = Flipkart[['product_name','retail_price','discounted_price']]

# renaming product_name as Product name in Flipkar,
# retail_price as Retail Price in Flipkart,discounted_price as Discounted Price in Flipkart

Flipkart.rename(columns = {'product_name':'Product name in Flipkar','retail_price':'Retail Price in Flipkart',
                        'discounted_price':'Discounted Price in Flipkart'}, inplace = True)

Flipkart

Flipkart.isna().sum() # Checking for none value

mean1 = Flipkart['Retail Price in Flipkart'].mean().round()
 mean1

# Replacing none values with the mean

Flipkart['Retail Price in Flipkart'].fillna(value=mean1, inplace=True)

Flipkart.isna().sum()

mean2 = Flipkart['Discounted Price in Flipkart'].mean().round()
Flipkart['Discounted Price in Flipkart'].fillna(value=mean2, inplace=True)

Flipkart.isna().sum()

Amazon = pd.read_csv('/content/drive/MyDrive/amz_com-ecommerce_sample.csv',encoding= 'unicode_escape')
Amazon.head() #uploading Amazon dataset

Amazon.columns

# Using important column

Amazon = Amazon[['product_name','retail_price','discounted_price']]

# Replace product_name as Product name in Amazon,retail_price as Retail Price in Amazon,
# discounted_price as Discounted Price in Amazon.

Amazon.rename(columns = {'product_name':'Product name in Amazon','retail_price':'Retail Price in Amazon',
                        'discounted_price':'Discounted Price in Amazon'}, inplace = True)

Amazon

Amazon.isna().sum() # Checking none value

# Matching similar product from flipkart and Amazon

result = pd.concat([Flipkart, Amazon], axis=1)
result.head()